import type { Metadata } from "next";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./assets/basic/index.scss";
import styles from "./layout.module.scss";
import Header from "@/components/Header/Header";
import { ThemeProvider } from "@mui/material";
import theme from "@/lib/theme";
import { ProductsProvider } from "@/components/Providers/ProductsProvider";
import { BasketProvider } from "@/components/Providers/BasketProvider";
import { SortingProvider } from "@/components/Providers/SortingProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProductsProvider>
        <SortingProvider>
          <BasketProvider>
            <ThemeProvider theme={theme}>
              <body>
                <div className={styles.wrapperPage}>
                  <Header />
                  {children}
                </div>
              </body>
            </ThemeProvider>
          </BasketProvider>
        </SortingProvider>
      </ProductsProvider>
    </html>
  );
}
